config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :minous do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:destroy, :edit, :update]

  get 'minouboard', to: 'pages#minouboard'
  get 'emprunts', to: 'pages#emprunts'
  get 'historique', to: 'pages#historique'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minou.rb
class Minou < ApplicationRecord
  belongs_to :user
  has_many :rentals
  mount_uploader :photo, PhotoUploader

  # Species & personalities definition
  SIZES         = %w(petit moyen grand)
  SPECIES       = %w(chat lion tigre lynx panthère)
  PERSONALITIES = %w(grumpy susceptible sournois espiègle têtu simplet dragueur calin)

  # Validations
  validates :name,          presence: true,   uniqueness: true
  validates :size,          presence: true,   inclusion: { in: SIZES }
  validates :specie,        presence: true,   inclusion: { in: SPECIES }
  validates :age,           presence: true,   numericality: true
  validates :personality,   presence: true,   inclusion: { in: PERSONALITIES }
  validates :description,   presence: true
  validates :daily_price,   presence: true,   numericality: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :minou

  # Validations
  validates :begin_date,  presence: true
  validates :end_date,    presence: true # Devra etre superieur a begin_date, a faire une fois les date picker done
  validates :user,        presence: true
  validates :minou,       presence: true
  # A rajouter lorsque les date picker auront ete finalises
  # validates :rental_price,
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :minous
  has_many :rentals
  mount_uploader :photo, PhotoUploader

  validates :first_name, presence: :true, allow_blank: :false
  validates :last_name, presence: :true, allow_blank: :false
  validates :address, presence: :true, allow_blank: :false

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo])

     # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:address, :photo])
   end
end

app/controllers/minous_controller.rb
class MinousController < ApplicationController
  before_action :set_minou, only: [:show, :edit, :destroy, :update]


  def index
    @minou_species = ["Toutes"] + Minou::SPECIES
    @minou_personnalities = ["Tous"] + Minou::PERSONALITIES
    # On recupere la requete de geoloc
    if params[:query] != nil
      @users = User.near(params[:query], 20)
      id = @users.map { |u| u.id }
      @query = params[:query]
      # Si filtre alors les minous sont differents
      if params[:specie_param] && params[:personality]
        if params[:specie_param] == "Toutes" && params[:personality] == "Tous"
          @minous = Minou.where(user_id: id)
        elsif params[:specie_param] == "Toutes"
          @minous = Minou.where(personality: params[:personality], user_id: id)
        elsif params[:personality] == "Tous"
          @minous = Minou.where(specie: params[:specie_param], user_id: id)
        else
          @minous = Minou.where(specie: params[:specie_param], personality: params[:personality], user_id: id)
        end
      else
      #   @minous = Minou.where(specie: params[:specie_param], personality: params[:personality], user_id: id)
      # elsif params[:specie]
      #   @minous = Minou.where(specie: params[:specie_param], user_id: id)
      # elsif params[:personality]
      #   @minous = Minou.where(personality: params[:personality], user_id: id)
      # else
      @minous = Minou.where(user_id: id)
      end
      # end
      @markers = @minous.map do |minou|
        {
          lat: minou.user.latitude,
          lng: minou.user.longitude
        }
        end
    else
      @minous = Minou.all
      @markers = @minous.map do |minou|
        {
          lat: minou.user.latitude,
          lng: minou.user.longitude
        }
      end
    end
    # @minous = Minou.all
    render layout: "index_layout"
  end

  def show
    @minou = Minou.find(params[:id])
    @rental = Rental.new
    @rentals = Rental.where(minou: @minou)
  end

  def new
    @minou = Minou.new
  end

  def create
    @minou = Minou.new(minou_params)
    @minou.user = current_user
    if @minou.save
      redirect_to minouboard_path(@minou)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @minou.update(minou_params)
    redirect_to minous_path
  end

  def destroy
    @minou.destroy
    redirect_to minouboard_path
  end

  private

  def set_minou
    @minou = Minou.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def minou_params
    params.require(:minou).permit(:name, :size, :specie, :age, :personality, :description, :daily_price, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    render layout: "homepage"
  end

  def minouboard
    @minous = current_user.minous
  end

  def emprunts
    @rentals = current_user.rentals
  end

  def historique
    @rentals = current_user.rentals
    # Calcul du solde de minoucoins
    @sold = 0
    @date = Date.today
    @rentals = Rental.where("rentals.begin_date < ?", @date)
    @rentals.each { |rental| @sold += rental.rental_price }
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def create
    @rental = Rental.new(rental_params)
    # Add the corresponding user and minou to rental
    @rental.user = current_user
    minou = Minou.find(params[:minou_id])
    @rental.minou = minou
    @rental.status = "request"
    # Rental price calculus a faire quand les date picker seront done
    @rental.begin_date = Date.parse(params[:rental][:begin_date][0..9])
    @rental.end_date = Date.parse(params[:rental][:end_date])
    # Rental price calculus
    @rental.rental_price = minou.daily_price * ( @rental.end_date - @rental.begin_date ).to_i
    # If save ok, redirect to minouboard
    if @rental.save
      redirect_to emprunts_path
    else
      render "minous/show"
    end
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update(rental_params)
    redirect_to minouboard_path
  end


   def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to emprunts_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def rental_params
    params.require(:rental).permit(:begin_date, :end_date, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

      <%= render "shared/search-bar-navbar-index" %>

    <%= render 'shared/flashes' %>
    <div class="page-content-margin-navbar">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
    <%= javascript_pack_tag 'application' %> <!-- Importe les plugin js de app/javascript/packs/application.js -->

  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/transparent_navbar" %>
    <%= render 'shared/flashes' %>
    <div class="page-content-margin-navbar">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/minous/index.html.erb
<div class="wrapper">
  <div class="container margin-kill">

    <!-- Champs de filtre -->

    <div class="filters">
<!--       <div class="col-12 col-sm-6 col-md-4">
 -->
          <div class="filter">
          <%= form_tag minous_path, method: :get, class: "form-inline" do %>
          <%= hidden_field_tag :query, @query %>

          <%= label_tag :specie_param, 'Espèce' %>
          <%= select_tag :specie_param, options_for_select(@minou_species, params[:specie_param]), label: "Espèce", class: "form-control" %>
          <%= label_tag :personality, 'Caractère' %>
          <%= select_tag :personality, options_for_select(@minou_personnalities, params[:personality]), label: "Caractère",
            class: "form-control" %>

          </div>

          <div class="filter">
            <%= submit_tag 'Filtrer', class: "filter-button" %>
            <%= link_to "Effacer", minous_path(query: @query), class: "filter-button-reinitialiser "  %>

          </div>
        <% end %>
 <!--      </div> -->
    </div>
   <p id="results"> <%= @minous.length %> résultats</p>



    <div class="row">
      <% @minous.each do |minou| %>
        <%= link_to minou_path(minou) do %>
          <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
              <% if minou.photo? %>
                <div class="card_body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0)), url('<%= cl_image_path minou.photo, height: 400, width: 400, crop: :fill %>')">
                  <h1 class="card_title"><%= minou.name %></h1>
                </div>
                <% else %>
                <div class="card_body" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0)), url("https://source.unsplash.com/400x400/?kitten,<%=minou.name%>");'>
                  <h1 class="card_title"><%= minou.name %></h1>
                </div>
              <% end %>
              <div class="card_content">
                <p id="specie"><%= minou.specie %></p>
                <p id="personality"><%= minou.personality %></p>
                <p id="price"><%= minou.daily_price %> Kitokens par jour</p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="mappy" style="position: relative; overflow:hidden">
    <div
      id="map"
      style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; background-color: rgb(229, 227, 223);"
      data-markers="<%= @markers.to_json %>"
    ></div>
  </div>
</div>

app/views/pages/emprunts.html.erb
<div class="minouboard-navbar">
  <%= link_to "Mes Minous", minouboard_path, :class => current_class?(minouboard_path) %>
  <%= link_to "Minoucations", emprunts_path, :class => current_class?(emprunts_path) %>
  <%= link_to "Historique", historique_path, :class => current_class?(historique_path) %>
</div>

<div class="wrapper">
  <div class="container">
    <div class="row">
      <% @rentals.each do |rental| %>
      <% if rental.end_date > Date.today%>
      <%= link_to minou_path(rental.minou) do %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="card">
          <% if rental.minou.photo? %>
          <div class="card_body" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path rental.minou.photo, height: 400, width: 400, crop: :fill %>')">
            <% else %>
            <div class="card_body" style='background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url("https://source.unsplash.com/400x400/?kitten,<%=rental.minou.name%>");'>
              <% end %>
              <h1 class="card_title"><%= rental.minou.name %></h1>
              <div id = "loc_status">
                <% if rental.status == "request" %>
                <p id="loc_pending">En attente</p>
                <% elsif rental.status == "confirmed" %>
                <p id="loc_confirmed">Confirmée</p>
                <% elsif rental.status == "free" %>
                <p id="loc_refused"> Refusée</p>
                <% end %>
              </div>
            </div>
            <div class="card_content">
              <p id="specie"><%= rental.minou.specie %></p>
              <p id="personality"><%= rental.minou.personality %></p>
              <p id="personality"> <i class="far fa-calendar-alt"></i> <%= rental.begin_date.strftime("%e %b %Y") %> <i class="fas fa-arrow-right"></i> <%= rental.end_date.strftime("%e %b %Y ") %></p>
            </div>
            <%= link_to rental, method: :delete, data: { confirm: 'Annuler la location ?'} do %>
              <% if rental.status != "free"%>
              <p class="archive_button">Annuler la location</p>
              <% else %>
              <p class="archive_button">Archiver la demande</p>
              <% end %>
              <% end %>
          </div>
        </div>
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/historique.html.erb
<div class="minouboard-navbar">
  <%= link_to "Mes Minous", minouboard_path, :class => current_class?(minouboard_path) %>
  <%= link_to "Minoucations", emprunts_path, :class => current_class?(emprunts_path) %>
  <%= link_to "Historique", historique_path, :class => current_class?(historique_path) %>
</div>

<div class="wrapper">
  <div class="container">

      <h4>Mon solde : <span class="sold"> <%= @sold %> </span> <%= image_tag "logo.png", height: 45, id: "minou_coin_logo" %> </h4>
      <!-- Boucle sur les rentals du user -->
      <ul class="inbox">
        <% @rentals.each do |rental| %>
        <% if rental.end_date < Date.today%>
          <li class="message">
            <div class="avatar-box">
              <%= image_tag rental.minou.photo, height: 120, width: 120, crop: :center, class: "big-avatar" %>
              <%= image_tag rental.user.photo, height: 50, width: 50, crop: :center, class: "small-avatar" %>
            </div>

            <div class="message-details">
              <h1 id="specie"> <%= rental.minou.specie %> </h1>
              <h1 id="name"> <%= rental.minou.name %> </h1>
              <h2> <i class="far fa-calendar-alt"></i> <%= rental.begin_date.strftime("%e %b") %> <i class="fas fa-arrow-right"></i> <%= rental.end_date.strftime("%e %b") %> </h2>
              <p> <%= (rental.end_date - rental.begin_date).to_i %> jours</p>
            </div>
            <div class="message-content">
              <% hash_avis = {avis1: "L'un des meilleurs minous que j'ai connu, doux, attentionné, le poil soyeux, à reprendre de toute urgence même s'il peut être parfois irritable.", avis2: "Un Minou tout à fait exceptionnel, il a su répondre à toutes mes attentes. Un déchirement de le rendre à son propriétaire, quel chanceux !!😀😀😀", avis3: "Un Minou d'amour 😍😍😍", avis4: "Dur à apprivoiser mais une fois le lien de confiance atteint, la complicité est totale",avis5: "Chaud le minou chaud !" }%>
              <p> <%= hash_avis.values.sample %></p>
            </div>
            <div class="message-status">
              <h2 id="minou-coin"> + <%= rental.rental_price %> </h2>
              <h2>MinouCoins <%= image_tag "logo.png", height: 25 %> </h2>
            </div>
          </li>
        <% end %>
        <% end %>

      </ul>

  </div>
</div>

app/views/pages/minouboard.html.erb
<!-- Menu 2 start -->

<div class="minouboard-navbar">
  <%= link_to "Mes Minous", minouboard_path, :class => current_class?(minouboard_path) %>
  <%= link_to "Minoucations", emprunts_path, :class => current_class?(emprunts_path) %>
  <%= link_to "Historique", historique_path, :class => current_class?(historique_path) %>
</div>

<!-- Content start -->
<div class="wrapper">
 <div class="container">
   <div class="row">
     <% @minous.each do |minou| %>
     <%= link_to minou_path(minou) do %>
     <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="card">
       <% if minou.photo? %>
       <div class="card_body" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= cl_image_path minou.photo, height: 400, width: 400, crop: :fill %>')">
        <% else %>
        <div class="card_body" style='background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url("https://source.unsplash.com/400x400/?kitten,<%=minou.name%>");'>
          <% end %>
          <h1 class="card_title"><%= minou.name %></h1>
          <p class="dash_card_actions">
           <%= link_to edit_minou_path(minou) do %>
           <i class="far fa-edit"></i>
           <% end %>
           <%= link_to minou, method: :delete, data: { confirm: 'Minoupauser ton minou ?'} do %>
           <i class="far fa-trash-alt"></i>
           <% end %>
         </p>
       </div>
       <div class="card_content">
         <p id="specie"><%= minou.specie %></p>
         <p id="personality"><%= minou.personality %></p>
         <p id="price"><%= minou.daily_price %> Kitokens par jour</p>
       </div>
       <% minou.rentals.select {|rental| rental.status == "request"}.each do |rental|%>
       <div class="accept_refuse_body">
        <%= cl_image_tag rental.user.photo, height: 46, width: 46, crop: :fill, class: "avatar-little" %>
        <p id="accept_refuse_title"><%= rental.user.first_name %> veut accueillir <%= minou.name %></p>
        <p class="date_accept_refuse_rental"><i class="far fa-calendar-alt"></i> <%= rental.begin_date.strftime("%e %b %Y ") %> <i class="fas fa-arrow-right"></i> <%= rental.end_date.strftime("%e %b %Y") %></p>
        <%= simple_form_for rental do |f| %>
        <div class="accept_refuse_buttons">
         <%= f.input :status, as: :hidden, input_html: { value: 'confirmed' } %>
         <button type="submit" class="accepted-button"><i class="fas fa-check"></i></button>
         <% end %>
         <%= simple_form_for rental do |f| %>
         <%= f.input :status, as: :hidden, input_html: { value: 'free' } %>
         <button type="submit" class="refused-button"><i class="fas fa-times"></i></button>
         <% end %>
       </div>
     </div>
     <% end %>
   </div>
 </div>
 <% end %>
 <% end %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-minou">
  <!-- Logo -->
  <%= link_to minous_path, class: "navbar-minou-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-minou-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Minouboard", minouboard_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Profil", edit_user_registration_path, class: "navbar-minou-item navbar-minou-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-minou-item">
        <div class="dropdown">
          <!-- <%# if current_user.photo? %> -->
             <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-minou-menu", 'data-toggle' => 'dropdown' %>
              <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %>
                </li>
              </ul>

          <%# end %>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Inscription", new_user_registration_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-minou-item navbar-minou-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-minou-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
        <li><%= link_to "Partager mon minou", new_minou_path %></li>
        <li><%= link_to "Minouboard", minouboard_path %></li>
        <li><%= link_to "Profil", edit_user_registration_path %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-bar-navbar-index.html.erb
<div class="navbar-minou">
  <div class="logo-searchbar">
  <!-- Logo -->
    <%= link_to minous_path, class: "navbar-minou-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>

    <div class="banner-search-navbar">
      <div class="form-container-navbar">
      <%= form_tag minous_path, class: "form-inline form-navbar",  method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control ou-minou",
        name: "query",
        id: "navbar_search",
        placeholder: "📍 Paris, Londres",
        autocomplete: "on"
        %>
        <button type="submit" class="search-button fas fa-search"></i></button>
      <% end %>
    </div>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-minou-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Minouboard", minouboard_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Profil", edit_user_registration_path, class: "navbar-minou-item navbar-minou-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-minou-item">
        <div class="dropdown">
          <!-- <%# if current_user.photo? %> -->
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-minou-menu", 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>

          <%# end %>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to "Inscription", new_user_registration_path, class: "navbar-minou-item navbar-minou-link" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-minou-item navbar-minou-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-minou-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
        <li><%= link_to "Partager mon minou", new_minou_path %></li>
        <li><%= link_to "Minouboard", minouboard_path %></li>
        <li><%= link_to "Profil", edit_user_registration_path %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_transparent_navbar.html.erb
<div class="navbar-transparent">
  <!-- Logo -->
  <%= link_to minous_path, class: "navbar-minou-brand" do %>
    <%= image_tag "minou_logo_white.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-minou-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item white-navbar-minou-link" %>
      <%= link_to "Minouboard", minouboard_path, class: "navbar-minou-item white-navbar-minou-link" %>
      <%= link_to "Profil", edit_user_registration_path, class: "navbar-minou-item white-navbar-minou-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-minou-item">
        <div class="dropdown">
          <!-- <%# if current_user.photo? %> -->
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-minou-menu", 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>

          <%# end %>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Partager mon Minou", new_minou_path, class: "navbar-minou-item white-navbar-minou-link" %>
      <%= link_to "Inscription", new_user_registration_path, class: "navbar-minou-item white-navbar-minou-link" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-minou-item white-navbar-minou-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-minou-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-minou-dropdown-menu">
        <li><%= link_to "Partager mon minou", new_minou_path %></li>
        <li><%= link_to "Minouboard", minouboard_path %></li>
        <li><%= link_to "Profil", edit_user_registration_path %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>